# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'

target 'FitnessTrackerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseAuth'
  pod 'Firebase'

  target 'FitnessTrackerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitnessTrackerAppUITests' do
    # Pods for testing
  end

end
